### PR TITLE
Add a possibility to inc/dec gauges

### PR DESCRIPTION
**Pull request by snusmu**

### CODE REVIEW

**Comment by euskadi31** [comment]
Hi @snusmu,

Thank you for contribution !!

Everything seems good to me, it would just be necessary to add unit tests.

**Comment by snusmu** [comment]
hi @euskadi31 

by unit tests, do you mean adding some asserts for the new functions to tests/statsd.cpp ?
im not sure though if i get how the testing process works

what i tried:
1. run make test
2. run a resulting binary ./build/Release/bin/statsd-test

this outputs:
```
StatsD Version : 1.0.0-3-g315efec
test.site.homepage.load:1500|ms
test.server.http.error.404:1|c
test.server.http.error.404:-1|c
test.site.auth.success:4|c
a.gauge.node:8|g
```

i can add asserts there - but for some reason asserts in the resulting binary dont seem to abort even if given failing conditions.
i mean, after adding a simple assert(false) like so: f.ex. https://github.com/snusmu/statsd-cpp/commit/362e64149f9e5c5297c3adb2fa5373bde2d66ec1, test binary does not abort, runs the same way.
Am i doing something wrong? im on ubuntu 18, gcc 7.5.0

Also shouldnt the condition here https://github.com/euskadi31/statsd-cpp/blob/master/test/statsd.cpp#L105 be (i >5) rather than i==5 ? 
loop seems to exit early otherwise (case n5, "a.graphite.set:12|s" is missing in the above output)

**Comment by euskadi31** [comment]
> by unit tests, do you mean adding some asserts for the new functions to tests/statsd.cpp ?

Yes

> im not sure though if i get how the testing process works
> 
> what i tried:
> 
> 1. run make test
> 2. run a resulting binary ./build/Release/bin/statsd-test

Just run `make test`

> Also shouldnt the condition here https://github.com/euskadi31/statsd-cpp/blob/master/test/statsd.cpp#L105 be (i >5) rather than i==5 ?
> loop seems to exit early otherwise (case n5, "a.graphite.set:12|s" is missing in the above output)
Yes indeed

**Comment by euskadi31** [comment]
I'll put the CI back in place tonight

**Comment by snusmu** [comment]
Allright i added the asserts. 
Still, similarly to what i mentioned regarding the asserts not aborting, for me `make test` always shows Passed, regardless of  what is in the asserts..

**Comment by euskadi31** [comment]
ok, i'm going to watch what is happening tonight

**Comment by euskadi31** [comment]
@snusmu I am curious, you use this project in which case? Personal project or in your company ?

**Comment by snusmu** [comment]
@euskadi31 we use it internally so our softwae to send stats to telegraf->influx->grafana

**Comment by euskadi31** [comment]
Ok, great !

Thank You for your contribution !

**Comment by snusmu** [comment]
@euskadi31 Well, first of all thank you :)

**Pull request merged**
